dist: trusty
addons:
  chrome: stable
  firefox: latest
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - BROWSER=chrome
  - BROWSER=firefox
before_install:
  - pip install flake8 webdriverdownloader pytest pytest-allure-adaptor pytest-localserver pytest-cov coveralls
  - webdriverdownloader chrome firefox
install: python setup.py install
script:
  - flake8 src testing --max-line-length=100
  - py.test -v --cov widgetastic_bootstrap --cov-report term-missing --alluredir allure/
after_success:
  - coveralls
